#!/bin/bash
tmpDir=$(mktemp -d /Users/jamall/workspace/krueger/cromwell-executions/helloHaplotypeCaller/d5972695-8ace-4221-aab5-5720b3b448f3/call-haplotypeCaller/execution/tmp.XXXXXX) 
export _JAVA_OPTIONS=-Djava.io.tmpdir=$tmpDir
export TMPDIR=$tmpDir

(
cd /Users/jamall/workspace/krueger/cromwell-executions/helloHaplotypeCaller/d5972695-8ace-4221-aab5-5720b3b448f3/call-haplotypeCaller/execution
java -jar /Users/jamall/workspace/krueger/cromwell-executions/helloHaplotypeCaller/d5972695-8ace-4221-aab5-5720b3b448f3/call-haplotypeCaller/inputs/Users/jamall/workspace/krueger/./lib/GenomeAnalysisTK.jar \
     -T HaplotypeCaller \
     -R /Users/jamall/workspace/krueger/cromwell-executions/helloHaplotypeCaller/d5972695-8ace-4221-aab5-5720b3b448f3/call-haplotypeCaller/inputs/Users/jamall/workspace/krueger/./sample_data/ref/human_g1k_b37_20.fasta \
     -I /Users/jamall/workspace/krueger/cromwell-executions/helloHaplotypeCaller/d5972695-8ace-4221-aab5-5720b3b448f3/call-haplotypeCaller/inputs/Users/jamall/workspace/krueger/./sample_data/inputs/NA12878_wgs_20.bam \
     -o NA12878.raw.indels.snps.vcf
)
echo $? > /Users/jamall/workspace/krueger/cromwell-executions/helloHaplotypeCaller/d5972695-8ace-4221-aab5-5720b3b448f3/call-haplotypeCaller/execution/rc.tmp
(
cd /Users/jamall/workspace/krueger/cromwell-executions/helloHaplotypeCaller/d5972695-8ace-4221-aab5-5720b3b448f3/call-haplotypeCaller/execution

)
sync
mv /Users/jamall/workspace/krueger/cromwell-executions/helloHaplotypeCaller/d5972695-8ace-4221-aab5-5720b3b448f3/call-haplotypeCaller/execution/rc.tmp /Users/jamall/workspace/krueger/cromwell-executions/helloHaplotypeCaller/d5972695-8ace-4221-aab5-5720b3b448f3/call-haplotypeCaller/execution/rc
