gprob<-matrix(scan("names_f_tran_common_loci.txt", n = 199 * 1894, sep = " ", what = 'character'), nrow=199,ncol=1894,byrow=T)
gprobMat<-gprob[,-c(1:2)]
gprobMat2<-matrix(as.numeric(gprobMat),nrow=199,ncol=1894,byrow=F)
pcg<-prcomp(gprobMat2,center=TRUE,scale=FALSE)
library(MASS)
k2<-kmeans(pcg$x[,1:5],2,iter.max=10,nstart=10,algorithm="Hartigan-Wong")
k3<-kmeans(pcg$x[,1:5],3,iter.max=10,nstart=10,algorithm="Hartigan-Wong")
k4<-kmeans(pcg$x[,1:5],4,iter.max=10,nstart=10,algorithm="Hartigan-Wong")
k5<-kmeans(pcg$x[,1:5],5,iter.max=10,nstart=10,algorithm="Hartigan-Wong")
k6<-kmeans(pcg$x[,1:5],6,iter.max=10,nstart=10,algorithm="Hartigan-Wong")
k7<-kmeans(pcg$x[,1:5],7,iter.max=10,nstart=10,algorithm="Hartigan-Wong")
k8<-kmeans(pcg$x[,1:5],8,iter.max=10,nstart=10,algorithm="Hartigan-Wong")
k9<-kmeans(pcg$x[,1:5],9,iter.max=10,nstart=10,algorithm="Hartigan-Wong")
k10<-kmeans(pcg$x[,1:5],10,iter.max=10,nstart=10,algorithm="Hartigan-Wong")


ldak2<-lda(x=pcg$x[,1:5],grouping=k2$cluster,CV=TRUE)
ldak3<-lda(x=pcg$x[,1:5],grouping=k3$cluster,CV=TRUE)
ldak4<-lda(x=pcg$x[,1:5],grouping=k4$cluster,CV=TRUE)
ldak5<-lda(x=pcg$x[,1:5],grouping=k5$cluster,CV=TRUE)
ldak6<-lda(x=pcg$x[,1:5],grouping=k6$cluster,CV=TRUE)
ldak7<-lda(x=pcg$x[,1:5],grouping=k7$cluster,CV=TRUE)
ldak8<-lda(x=pcg$x[,1:5],grouping=k8$cluster,CV=TRUE)
ldak9<-lda(x=pcg$x[,1:5],grouping=k9$cluster,CV=TRUE)
ldak10<-lda(x=pcg$x[,1:5],grouping=k10$cluster,CV=TRUE)

write.table(round(ldak2$posterior,5),file="ldak2.txt",quote=F,row.names=F,col.names=F)
write.table(round(ldak3$posterior,5),file="ldak3.txt",quote=F,row.names=F,col.names=F)
write.table(round(ldak4$posterior,5),file="ldak4.txt",quote=F,row.names=F,col.names=F)
write.table(round(ldak5$posterior,5),file="ldak5.txt",quote=F,row.names=F,col.names=F)
write.table(round(ldak6$posterior,5),file="ldak6.txt",quote=F,row.names=F,col.names=F)
write.table(round(ldak7$posterior,5),file="ldak7.txt",quote=F,row.names=F,col.names=F)
write.table(round(ldak8$posterior,5),file="ldak8.txt",quote=F,row.names=F,col.names=F)
write.table(round(ldak9$posterior,5),file="ldak9.txt",quote=F,row.names=F,col.names=F)
write.table(round(ldak10$posterior,5),file="ldak10.txt",quote=F,row.names=F,col.names=F)
